function Hd = lowpass(N, Fpass, Fstop, Wpass, Wstop)
%LOWPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
% Generated on: 24-Nov-2013 18:15:59

% FIR least-squares Lowpass filter designed using the FIRLS function.

% All frequency values are in Hz.
Fs = 49164;  % Sampling Frequency

%N     = 10;    % Order
%Fpass = 1000;  % Passband Frequency
%Fstop = 2000;  % Stopband Frequency
%Wpass = 1;     % Passband Weight
%Wstop = 0.1;   % Stopband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop]);
Hd = b;

% [EOF]
