function Hd = lowpass(N, Fpass, Fstop, Wpass, Wstop)
%LOWPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
% Generated on: 05-Nov-2013 14:36:54

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 48000;  % Sampling Frequency

%N     = 100;   % Order
%Fpass = 1000;  % Passband Frequency
%Fstop = 2000;  % Stopband Frequency
%Wpass = 1;     % Passband Weight
%Wstop = 1;     % Stopband Weight
dens  = 20;    % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
           {dens});

Hd = b; %dfilt.dffir(b);

% [EOF]
